version: '3.8'
services:
  postgres:
    image: postgres:14
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: force-desk
    ports:
      - "5433:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  users-service:
    build: ./backend/users-service
    environment:
      DATABASE_URL: postgres://admin:admin@postgres:5432/force-desk
      JWT_SECRET: secret123
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "3001:3000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped

  incidents-service:
    build: ./backend/incidents-service
    environment:
      DATABASE_URL: postgres://admin:admin@postgres:5432/force-desk
      JWT_SECRET: secret123
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "3002:3000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
    restart: unless-stopped

  web:
    build: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - users-service
      - incidents-service
    restart: unless-stopped

volumes:
  pgdata: